### ISSUE TITLE
ResponseValidator: how to handle mime-type with character encoding details

### ISSUE THREAD

**Issue by Leemur89** [MarketSquare/robotframework-openapi-libcore#20]
Hello,
This is the issue described [here](https://github.com/python-openapi/openapi-core/issues/378) and I think has been fixed in version 0.19.0 of openapi-core
Could you please bump the openapi-core version in project.toml? Or at least loosen the dependency `openapi-core>=0.18.0` ?

**Comment by robinmackaij** [comment]
I'll take a look at that update later this week. I'm not inclined to loosen that particular dependency since the author of openapi-core has the tendency to make backwards-incompatible changes in the updates (which is technically allowed for `0.x` releases).

**Comment by robinmackaij** [comment]
The latest robotframework-openapitools should address this.
